spring.application.name=restapi
server.port = 8090

#Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/expensetransactions
spring.datasource.username=root
spring.datasource.password=$pkopdlgSQL25

#jpa properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.context-path=/api/v1